/**
 * Test data for VB6 Properties Window
 * Contains sample controls with typical VB6 properties
 */

import { Control } from '../../../context/types';

export const sampleTextBox: Control = {
  id: 1,
  name: 'Text1',
  type: 'TextBox',
  x: 100,
  y: 50,
  width: 120,
  height: 20,
  properties: {
    Name: 'Text1',
    Text: 'Hello World',
    Left: 100,
    Top: 50,
    Width: 120,
    Height: 20,
    Font: JSON.stringify({ name: 'MS Sans Serif', size: 8, bold: false, italic: false }),
    BackColor: '#FFFFFF',
    ForeColor: '#000000',
    BorderStyle: '1 - Fixed Single',
    Enabled: true,
    Visible: true,
    TabStop: true,
    TabIndex: 0,
    Locked: false,
    MaxLength: 0,
    PasswordChar: '',
    MultiLine: false,
    ScrollBars: '0 - None',
    Alignment: '0 - Left Justify',
    ToolTipText: '',
    Tag: '',
    MousePointer: '0 - Default',
    CausesValidation: true,
    OLEDragMode: '0 - None',
    OLEDropMode: '0 - None',
    RightToLeft: false,
    HelpContextID: 0,
    WhatsThisHelpID: 0,
  },
  events: {},
};

export const sampleCommandButton: Control = {
  id: 2,
  name: 'Command1',
  type: 'CommandButton',
  x: 50,
  y: 100,
  width: 75,
  height: 25,
  properties: {
    Name: 'Command1',
    Caption: 'OK',
    Left: 50,
    Top: 100,
    Width: 75,
    Height: 25,
    Font: JSON.stringify({ name: 'MS Sans Serif', size: 8, bold: false, italic: false }),
    BackColor: '#C0C0C0',
    ForeColor: '#000000',
    Enabled: true,
    Visible: true,
    TabStop: true,
    TabIndex: 1,
    Default: false,
    Cancel: false,
    Picture: '',
    Style: '0 - Standard',
    ToolTipText: '',
    Tag: '',
    MousePointer: '0 - Default',
    CausesValidation: true,
    OLEDragMode: '0 - None',
    OLEDropMode: '0 - None',
    RightToLeft: false,
    HelpContextID: 0,
    WhatsThisHelpID: 0,
    UseMaskColor: false,
    MaskColor: '#C0C0C0',
  },
  events: {},
};

export const sampleLabel: Control = {
  id: 3,
  name: 'Label1',
  type: 'Label',
  x: 20,
  y: 20,
  width: 60,
  height: 15,
  properties: {
    Name: 'Label1',
    Caption: 'Label1',
    Left: 20,
    Top: 20,
    Width: 60,
    Height: 15,
    Font: JSON.stringify({ name: 'MS Sans Serif', size: 8, bold: false, italic: false }),
    BackColor: '#8000000F',
    ForeColor: '#80000012',
    BackStyle: '1 - Opaque',
    BorderStyle: '0 - None',
    Enabled: true,
    Visible: true,
    AutoSize: false,
    WordWrap: false,
    Alignment: '0 - Left Justify',
    ToolTipText: '',
    Tag: '',
    MousePointer: '0 - Default',
    OLEDragMode: '0 - None',
    OLEDropMode: '0 - None',
    RightToLeft: false,
    HelpContextID: 0,
    WhatsThisHelpID: 0,
    UseMnemonic: true,
  },
  events: {},
};

export const sampleListBox: Control = {
  id: 4,
  name: 'List1',
  type: 'ListBox',
  x: 200,
  y: 50,
  width: 120,
  height: 100,
  properties: {
    Name: 'List1',
    Left: 200,
    Top: 50,
    Width: 120,
    Height: 100,
    Font: JSON.stringify({ name: 'MS Sans Serif', size: 8, bold: false, italic: false }),
    BackColor: '#80000005',
    ForeColor: '#80000008',
    Enabled: true,
    Visible: true,
    TabStop: true,
    TabIndex: 2,
    Sorted: false,
    MultiSelect: '0 - None',
    Style: '0 - Standard',
    IntegralHeight: true,
    ItemData: '',
    List: 'Item 1\nItem 2\nItem 3',
    ListCount: 3,
    ListIndex: -1,
    TopIndex: 0,
    ToolTipText: '',
    Tag: '',
    MousePointer: '0 - Default',
    CausesValidation: true,
    OLEDragMode: '0 - None',
    OLEDropMode: '0 - None',
    RightToLeft: false,
    HelpContextID: 0,
    WhatsThisHelpID: 0,
  },
  events: {},
};

export const sampleCheckBox: Control = {
  id: 5,
  name: 'Check1',
  type: 'CheckBox',
  x: 150,
  y: 100,
  width: 100,
  height: 20,
  properties: {
    Name: 'Check1',
    Caption: 'Check1',
    Left: 150,
    Top: 100,
    Width: 100,
    Height: 20,
    Font: JSON.stringify({ name: 'MS Sans Serif', size: 8, bold: false, italic: false }),
    BackColor: '#8000000F',
    ForeColor: '#80000012',
    Enabled: true,
    Visible: true,
    TabStop: true,
    TabIndex: 3,
    Value: '0 - Unchecked',
    Alignment: '0 - Left Justify',
    Style: '0 - Standard',
    Picture: '',
    DownPicture: '',
    DisabledPicture: '',
    ToolTipText: '',
    Tag: '',
    MousePointer: '0 - Default',
    CausesValidation: true,
    OLEDragMode: '0 - None',
    OLEDropMode: '0 - None',
    RightToLeft: false,
    HelpContextID: 0,
    WhatsThisHelpID: 0,
    UseMaskColor: false,
    MaskColor: '#C0C0C0',
  },
  events: {},
};

export const sampleOptionButton: Control = {
  id: 6,
  name: 'Option1',
  type: 'OptionButton',
  x: 300,
  y: 100,
  width: 100,
  height: 20,
  properties: {
    Name: 'Option1',
    Caption: 'Option1',
    Left: 300,
    Top: 100,
    Width: 100,
    Height: 20,
    Font: JSON.stringify({ name: 'MS Sans Serif', size: 8, bold: false, italic: false }),
    BackColor: '#8000000F',
    ForeColor: '#80000012',
    Enabled: true,
    Visible: true,
    TabStop: true,
    TabIndex: 4,
    Value: false,
    Alignment: '0 - Left Justify',
    Style: '0 - Standard',
    Picture: '',
    DownPicture: '',
    DisabledPicture: '',
    ToolTipText: '',
    Tag: '',
    MousePointer: '0 - Default',
    CausesValidation: true,
    OLEDragMode: '0 - None',
    OLEDropMode: '0 - None',
    RightToLeft: false,
    HelpContextID: 0,
    WhatsThisHelpID: 0,
    UseMaskColor: false,
    MaskColor: '#C0C0C0',
  },
  events: {},
};

export const sampleComboBox: Control = {
  id: 7,
  name: 'Combo1',
  type: 'ComboBox',
  x: 350,
  y: 50,
  width: 120,
  height: 20,
  properties: {
    Name: 'Combo1',
    Text: '',
    Left: 350,
    Top: 50,
    Width: 120,
    Height: 20,
    Font: JSON.stringify({ name: 'MS Sans Serif', size: 8, bold: false, italic: false }),
    BackColor: '#80000005',
    ForeColor: '#80000008',
    Enabled: true,
    Visible: true,
    TabStop: true,
    TabIndex: 5,
    Style: '0 - Dropdown Combo',
    Sorted: false,
    List: 'Option A\nOption B\nOption C',
    ListCount: 3,
    ListIndex: -1,
    Locked: false,
    MaxLength: 0,
    ItemData: '',
    ToolTipText: '',
    Tag: '',
    MousePointer: '0 - Default',
    CausesValidation: true,
    OLEDragMode: '0 - None',
    OLEDropMode: '0 - None',
    RightToLeft: false,
    HelpContextID: 0,
    WhatsThisHelpID: 0,
    IntegralHeight: true,
  },
  events: {},
};

export const samplePictureBox: Control = {
  id: 8,
  name: 'Picture1',
  type: 'PictureBox',
  x: 50,
  y: 150,
  width: 100,
  height: 80,
  properties: {
    Name: 'Picture1',
    Left: 50,
    Top: 150,
    Width: 100,
    Height: 80,
    Font: JSON.stringify({ name: 'MS Sans Serif', size: 8, bold: false, italic: false }),
    BackColor: '#8000000F',
    ForeColor: '#80000012',
    BorderStyle: '1 - Fixed Single',
    Enabled: true,
    Visible: true,
    TabStop: true,
    TabIndex: 6,
    Picture: '',
    Stretch: false,
    AutoRedraw: false,
    AutoSize: false,
    ClipControls: true,
    ScaleMode: '1 - Twip',
    ScaleHeight: 80,
    ScaleWidth: 100,
    ScaleLeft: 0,
    ScaleTop: 0,
    DrawMode: '13 - Copy Pen',
    DrawStyle: '0 - Solid',
    DrawWidth: 1,
    FillColor: '#000000',
    FillStyle: '1 - Transparent',
    ToolTipText: '',
    Tag: '',
    MousePointer: '0 - Default',
    OLEDragMode: '0 - None',
    OLEDropMode: '0 - None',
    RightToLeft: false,
    HelpContextID: 0,
    WhatsThisHelpID: 0,
    Align: '0 - None',
    Appearance: '1 - 3D',
  },
  events: {},
};

export const allSampleControls = [
  sampleTextBox,
  sampleCommandButton,
  sampleLabel,
  sampleListBox,
  sampleCheckBox,
  sampleOptionButton,
  sampleComboBox,
  samplePictureBox,
];

export const sampleFormProperties = {
  Name: 'Form1',
  Caption: 'Form1',
  Left: 0,
  Top: 0,
  Width: 640,
  Height: 480,
  Font: JSON.stringify({ name: 'MS Sans Serif', size: 8, bold: false, italic: false }),
  BackColor: '#8000000F',
  ForeColor: '#80000012',
  BorderStyle: '2 - Sizable',
  ControlBox: true,
  MaxButton: true,
  MinButton: true,
  Moveable: true,
  Enabled: true,
  Visible: true,
  AutoRedraw: false,
  ClipControls: true,
  DrawMode: '13 - Copy Pen',
  DrawStyle: '0 - Solid',
  DrawWidth: 1,
  FillColor: '#000000',
  FillStyle: '1 - Transparent',
  HasDC: false,
  Icon: '',
  KeyPreview: false,
  LinkMode: '0 - None',
  LinkTopic: '',
  MDIChild: false,
  NegotiateMenus: true,
  Picture: '',
  RightToLeft: false,
  ScaleHeight: 480,
  ScaleLeft: 0,
  ScaleMode: '1 - Twip',
  ScaleTop: 0,
  ScaleWidth: 640,
  ShowInTaskbar: true,
  StartUpPosition: '2 - CenterScreen',
  Tag: '',
  WindowState: '0 - Normal',
  HelpContextID: 0,
  WhatsThisHelp: false,
  WhatsThisButton: false,
};
