export const getDefaultProperties = (type: string, id: number) => {

  const baseProps = {
    id,
    type,
    name: `${type}${id}`,
    x: 100,
    y: 100,
    visible: true,
    enabled: true,
    tabIndex: id,
    tabStop: true,
    tag: '',
    toolTipText: '',
  };

  const typeSpecificProps: { [key: string]: any } = {
    CommandButton: {
      width: 89,
      height: 25,
      caption: `Command${id}`,
      default: false,
      cancel: false,
      style: 0,
      backColor: '#C0C0C0',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
    },
    Label: {
      width: 65,
      height: 17,
      caption: `Label${id}`,
      autoSize: false,
      alignment: 0,
      backStyle: 0,
      backColor: '#8080FF',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
      wordWrap: false,
      borderStyle: 0,
    },
    TextBox: {
      width: 121,
      height: 21,
      text: '',
      multiLine: false,
      scrollBars: 0,
      alignment: 0,
      backColor: '#FFFFFF',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
      maxLength: 0,
      passwordChar: '',
      locked: false,
      borderStyle: 1,
    },
    Frame: {
      width: 121,
      height: 97,
      caption: `Frame${id}`,
      backColor: '#C0C0C0',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
    },
    CheckBox: {
      width: 121,
      height: 17,
      caption: `Check${id}`,
      value: 0,
      alignment: 0,
      backColor: 'transparent',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
    },
    OptionButton: {
      width: 121,
      height: 17,
      caption: `Option${id}`,
      value: false,
      alignment: 0,
      backColor: 'transparent',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
    },
    ListBox: {
      width: 121,
      height: 97,
      backColor: '#FFFFFF',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
      multiSelect: 0,
      sorted: false,
      style: 0,
      items: [],
    },
    ComboBox: {
      width: 121,
      height: 21,
      text: '',
      backColor: '#FFFFFF',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
      style: 0,
      sorted: false,
      items: [],
    },
    Timer: {
      width: 32,
      height: 32,
      interval: 0,
      enabled: true,
    },
    PictureBox: {
      width: 121,
      height: 97,
      backColor: '#C0C0C0',
      borderStyle: 1,
      picture: null,
      autoSize: false,
    },
    Image: {
      width: 100,
      height: 100,
      picture: '',
      stretch: false,
      appearance: 1,
      borderStyle: 0,
      enabled: true,
      visible: true,
      dragMode: 0,
    },
    Shape: {
      width: 100,
      height: 100,
      shape: 0,
      fillColor: '#FFFFFF',
      fillStyle: 1,
      borderColor: '#000000',
      borderStyle: 1,
      borderWidth: 1,
      backStyle: 1,
      visible: true,
      drawMode: 13,
    },
    Line: {
      width: 100,
      height: 100,
      x1: 0,
      y1: 0,
      x2: 100,
      y2: 100,
      borderColor: '#000000',
      borderStyle: 1,
      borderWidth: 1,
      drawMode: 13,
      visible: true,
    },
    HScrollBar: {
      width: 121,
      height: 17,
      min: 0,
      max: 32767,
      value: 0,
      smallChange: 1,
      largeChange: 1,
    },
    VScrollBar: {
      width: 17,
      height: 121,
      min: 0,
      max: 32767,
      value: 0,
      smallChange: 1,
      largeChange: 1,
    },
    DriveListBox: {
      width: 145,
      height: 21,
      drive: 'C:',
      backColor: '#FFFFFF',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
    },
    DirListBox: {
      width: 145,
      height: 135,
      path: 'C:\\',
      backColor: '#FFFFFF',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
    },
    FileListBox: {
      width: 145,
      height: 135,
      path: 'C:\\',
      pattern: '*.*',
      fileName: '',
      backColor: '#FFFFFF',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
      multiSelect: 0,
      archive: true,
      hidden: false,
      normal: true,
      readOnly: true,
      system: false,
    },
    Data: {
      width: 361,
      height: 28,
      caption: 'Data1',
      connect: 'Access',
      databaseName: '',
      recordSource: '',
      recordsetType: 1,
      options: 0,
      exclusive: false,
      readOnly: false,
      backColor: '#C0C0C0',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
      eofAction: 0,
      bofAction: 0,
    },
    ADODataControl: {
      width: 385,
      height: 28,
      caption: 'Adodc1',
      connectionString: '',
      commandType: 8,
      recordSource: '',
      cursorLocation: 3,
      cursorType: 3,
      lockType: 3,
      mode: 0,
      backColor: '#C0C0C0',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
      eofAction: 0,
      bofAction: 0,
    },
    OLE: {
      width: 193,
      height: 121,
      class: '',
      sourceDoc: '',
      sourceItem: '',
      displayType: 0,
      autoActivate: 0,
      autoVerbMenu: true,
      updateOptions: 0,
      sizeMode: 0,
      oleType: 2,
      oleTypeAllowed: 2,
      backColor: '#C0C0C0',
      backStyle: 1,
      borderStyle: 1,
    },
    Winsock: {
      width: 39,
      height: 39,
      protocol: 0,
      remoteHost: '',
      remotePort: 0,
      localPort: 0,
      localIP: '',
      state: 0,
    },
    Inet: {
      width: 39,
      height: 39,
      protocol: 4,
      url: '',
      proxy: '',
      accessType: 0,
      userName: '',
      password: '',
      requestTimeout: 60,
    },
    ProgressBar: {
      width: 121,
      height: 21,
      min: 0,
      max: 100,
      value: 0,
      backColor: '#C0C0C0',
      foreColor: '#0078D4',
    },
    Slider: {
      width: 121,
      height: 21,
      min: 0,
      max: 100,
      value: 0,
      orientation: 'horizontal',
      backColor: '#C0C0C0',
      foreColor: '#000000',
    },
    UpDown: {
      width: 17,
      height: 21,
      min: 0,
      max: 100,
      value: 0,
      increment: 1,
      orientation: 'vertical',
    },
    TabStrip: {
      width: 241,
      height: 145,
      tabs: ['Tab1', 'Tab2'],
      selectedIndex: 0,
      backColor: '#C0C0C0',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
    },
    Toolbar: {
      width: 241,
      height: 25,
      buttons: ['New', 'Open', 'Save'],
      backColor: '#C0C0C0',
      foreColor: '#000000',
    },
    ListView: {
      width: 121,
      height: 97,
      columns: ['Column1', 'Column2'],
      items: [
        { text: 'Item1', subItems: ['Sub1', 'Sub2'] },
        { text: 'Item2', subItems: ['Sub1', 'Sub2'] },
      ],
      view: 'report',
      backColor: '#FFFFFF',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
    },
    StatusBar: {
      width: 241,
      height: 21,
      panels: ['Ready'],
      backColor: '#C0C0C0',
      foreColor: '#000000',
    },
    ImageList: {
      width: 32,
      height: 32,
      images: [],
      imageWidth: 16,
      imageHeight: 16,
      backColor: '#FFFFFF',
      foreColor: '#000000',
    },
    TreeView: {
      width: 121,
      height: 97,
      nodes: ['Node1', 'Node2'],
      backColor: '#FFFFFF',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
    },
    DateTimePicker: {
      width: 121,
      height: 21,
      value: new Date().toISOString(),
      backColor: '#FFFFFF',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
    },
    MonthView: {
      width: 161,
      height: 161,
      value: new Date().toISOString().substring(0, 10),
      backColor: '#FFFFFF',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
    },
    RichTextBox: {
      width: 121,
      height: 97,
      text: '',
      scrollBars: 3,
      backColor: '#FFFFFF',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
      locked: false,
      borderStyle: 1,
    },
    ImageCombo: {
      width: 121,
      height: 21,
      text: '',
      items: [],
      images: [],
      imageWidth: 16,
      imageHeight: 16,
      style: 0,
      sorted: false,
      backColor: '#FFFFFF',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
    },
    Animation: {
      width: 121,
      height: 97,
      file: '',
      autoPlay: true,
      loop: true,
      backColor: '#000000',
    },
    FlatScrollBar: {
      width: 121,
      height: 17,
      min: 0,
      max: 32767,
      value: 0,
      smallChange: 1,
      largeChange: 1,
      orientation: 'horizontal',
      backColor: '#C0C0C0',
      foreColor: '#000000',
    },
    MaskedEdit: {
      width: 121,
      height: 21,
      text: '',
      mask: '',
      backColor: '#FFFFFF',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
    },
    WebBrowser: {
      width: 241,
      height: 181,
      url: 'about:blank',
    },
    DataGrid: {
      width: 241,
      height: 145,
      columns: [],
      data: [],
    },
    DataList: {
      width: 121,
      height: 97,
      rows: [],
    },
    DataCombo: {
      width: 121,
      height: 21,
      text: '',
      items: [],
    },
    DBList: {
      width: 120,
      height: 100,
      dataSource: '',
      dataField: '',
      rowSource: '',
      listField: '',
      boundColumn: 0,
      list: [],
      listCount: 0,
      listIndex: -1,
      text: '',
      boundText: '',
      selectedValue: null,
      matchEntry: 1,
      sorted: false,
      integralHeight: true,
      backColor: '#FFFFFF',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
    },
    DBCombo: {
      width: 120,
      height: 21,
      dataSource: '',
      dataField: '',
      rowSource: '',
      listField: '',
      boundColumn: 0,
      list: [],
      listCount: 0,
      listIndex: -1,
      text: '',
      boundText: '',
      selectedValue: null,
      style: 0,
      maxLength: 0,
      selLength: 0,
      selStart: 0,
      selText: '',
      matchEntry: 1,
      sorted: false,
      backColor: '#FFFFFF',
      foreColor: '#000000',
      font: { name: 'MS Sans Serif', size: 8, bold: false, italic: false, underline: false },
    },
    DataRepeater: {
      width: 241,
      height: 145,
      dataSource: '',
      dataMember: '',
      recordSource: '',
      readerHeight: 50,
      currentRecord: 0,
      recordCount: 0,
      repeaterItems: [],
      scrollBars: 2,
      allowAddNew: true,
      allowDelete: true,
      allowUpdate: true,
      appearance: 1,
      borderStyle: 1,
      backColor: '#ffffff',
      foreColor: '#000000',
    },
    MSChart: {
      width: 300,
      height: 200,
      chartType: 1,
      showLegend: true,
      legendLocation: 1,
      titleText: '',
      titleLocation: 1,
      data: {
        columnCount: 4,
        rowCount: 3,
        values: [[10, 20, 30, 40], [15, 25, 35, 45], [12, 22, 32, 42]],
        columnLabels: ['Q1', 'Q2', 'Q3', 'Q4'],
        rowLabels: ['Series 1', 'Series 2', 'Series 3']
      },
      autoIncrement: true,
      allowSeriesSelection: true,
      allowPointSelection: true,
      chartBackColor: '#FFFFFF',
      plotBackColor: '#F0F0F0',
      gridLineColor: '#C0C0C0',
      showGridLines: true,
      borderStyle: 1,
      chart3D: false,
      depth: 100,
      rotation: 20,
      elevation: 15,
      showXAxisLabels: true,
      showYAxisLabels: true,
      xAxisTitle: '',
      yAxisTitle: '',
    },
    PictureClip: {
      width: 100,
      height: 100,
      picture: '',
      stretch: false,
      rows: 1,
      cols: 1,
      clipX: 0,
      clipY: 0,
      clipWidth: 0,
      clipHeight: 0,
      graphicCell: 0,
      appearance: 1,
      borderStyle: 1,
      mousePointer: 0,
    },
    DataEnvironment: {
      width: 32,
      height: 32,
    },
    DataReport: {
      width: 241,
      height: 181,
    },
    CrystalReport: {
      width: 32,
      height: 32,
    },
    MediaPlayer: {
      width: 241,
      height: 181,
      file: '',
    },
    MMControl: {
      width: 241,
      height: 25,
      file: '',
    },
    GraphicsCanvas: {
      width: 241,
      height: 181,
      backColor: '#FFFFFF',
      foreColor: '#000000',
      fillColor: '#FFFFFF',
      fillStyle: 0,
      drawWidth: 1,
      drawStyle: 0,
      scaleMode: 1,
      autoRedraw: false,
      borderStyle: 1,
    },
    ActiveXControl: {
      width: 120,
      height: 80,
      progId: '',
      properties: {},
      events: {},
    },
  };

  return { ...baseProps, ...(typeSpecificProps[type] || {}) };
};
