import React, { useState, useEffect } from 'react';
import { X, Plus, Trash2, ChevronLeft, ChevronRight, Check, Database, Table, Columns, Layout, Code, Eye, Copy, Download, Settings, Link, Filter, Search, Grid, List, FileText, Target, Zap, RefreshCw, AlertTriangle, Info } from 'lucide-react';

// Types
export enum DataSourceType {
  ACCESS = 'Microsoft Access',
  SQL_SERVER = 'SQL Server',
  ORACLE = 'Oracle',
  MYSQL = 'MySQL',
  ODBC = 'ODBC Data Source',
  OLEDB = 'OLE DB Provider',
  ADO = 'ActiveX Data Objects'
}

export enum FormLayoutType {
  SINGLE = 'Single Record',
  TABULAR = 'Tabular (DataGrid)',
  MASTER_DETAIL = 'Master/Detail',
  COLUMNAR = 'Columnar Layout',
  FREEFORM = 'Freeform Design'
}

export enum ControlType {
  TEXTBOX = 'TextBox',
  LABEL = 'Label',
  COMBOBOX = 'ComboBox',
  LISTBOX = 'ListBox',
  CHECKBOX = 'CheckBox',
  DATAGRID = 'DataGrid',
  DBGRID = 'DBGrid',
  MASKED_EDIT = 'MaskedEdit',
  DATE_PICKER = 'DateTimePicker',
  RICH_TEXTBOX = 'RichTextBox',
  PICTURE_BOX = 'PictureBox'
}

export enum DataControlType {
  DATA_CONTROL = 'Data Control',
  ADO_DATA = 'ADO Data Control',
  REMOTE_DATA = 'Remote Data Control',
  CONNECTION_OBJECT = 'Connection Object',
  RECORDSET_OBJECT = 'Recordset Object'
}

export interface DatabaseConnection {
  id: string;
  name: string;
  type: DataSourceType;
  connectionString: string;
  provider: string;
  server?: string;
  database?: string;
  username?: string;
  password?: string;
  isConnected: boolean;
}

export interface DatabaseTable {
  id: string;
  name: string;
  schema: string;
  type: 'table' | 'view' | 'query';
  recordCount: number;
  columns: DatabaseColumn[];
}

export interface DatabaseColumn {
  id: string;
  name: string;
  displayName: string;
  dataType: string;
  length?: number;
  precision?: number;
  scale?: number;
  nullable: boolean;
  primaryKey: boolean;
  foreignKey: boolean;
  autoIncrement: boolean;
  defaultValue?: string;
}

export interface FormField {
  id: string;
  columnId: string;
  controlType: ControlType;
  label: string;
  required: boolean;
  readOnly: boolean;
  visible: boolean;
  tabOrder: number;
  validation?: {
    minLength?: number;
    maxLength?: number;
    minValue?: number;
    maxValue?: number;
    pattern?: string;
    customValidation?: string;
  };
  formatting?: {
    format?: string;
    alignment?: 'left' | 'center' | 'right';
    width?: number;
    height?: number;
  };
}

export interface NavigationButton {
  id: string;
  type: 'first' | 'previous' | 'next' | 'last' | 'add' | 'delete' | 'update' | 'cancel' | 'refresh';
  caption: string;
  enabled: boolean;
  visible: boolean;
}

export interface DataFormConfiguration {
  id: string;
  name: string;
  description: string;
  connection: DatabaseConnection;
  table: DatabaseTable;
  layoutType: FormLayoutType;
  dataControl: DataControlType;
  fields: FormField[];
  navigationButtons: NavigationButton[];
  formProperties: {
    caption: string;
    width: number;
    height: number;
    resizable: boolean;
    centerOnScreen: boolean;
    showInTaskbar: boolean;
    modal: boolean;
  };
  codeGeneration: {
    generateValidation: boolean;
    generateErrorHandling: boolean;
    generateNavigation: boolean;
    generateSearch: boolean;
    includeComments: boolean;
    useTryBlocks: boolean;
  };
}

interface DataFormWizardProps {
  isOpen: boolean;
  onClose: () => void;
  configuration?: DataFormConfiguration;
  onSave?: (configuration: DataFormConfiguration) => void;
}

export const DataFormWizard: React.FC<DataFormWizardProps> = ({
  isOpen,
  onClose,
  configuration,
  onSave
}) => {
  const [currentStep, setCurrentStep] = useState(1);
  const [wizardData, setWizardData] = useState<DataFormConfiguration>(() => configuration || {
    id: `form-${Date.now()}`,
    name: 'DataForm1',
    description: 'Data entry form generated by Data Form Wizard',
    connection: {
      id: 'conn-1',
      name: 'Northwind',
      type: DataSourceType.ACCESS,
      connectionString: 'Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\\Northwind.mdb',
      provider: 'Microsoft.Jet.OLEDB.4.0',
      database: 'Northwind.mdb',
      isConnected: true
    },
    table: {
      id: 'table-1',
      name: 'Customers',
      schema: 'dbo',
      type: 'table',
      recordCount: 91,
      columns: [
        {
          id: 'col-1',
          name: 'CustomerID',
          displayName: 'Customer ID',
          dataType: 'Text',
          length: 5,
          nullable: false,
          primaryKey: true,
          foreignKey: false,
          autoIncrement: false
        },
        {
          id: 'col-2',
          name: 'CompanyName',
          displayName: 'Company Name',
          dataType: 'Text',
          length: 40,
          nullable: false,
          primaryKey: false,
          foreignKey: false,
          autoIncrement: false
        },
        {
          id: 'col-3',
          name: 'ContactName',
          displayName: 'Contact Name',
          dataType: 'Text',
          length: 30,
          nullable: true,
          primaryKey: false,
          foreignKey: false,
          autoIncrement: false
        },
        {
          id: 'col-4',
          name: 'ContactTitle',
          displayName: 'Contact Title',
          dataType: 'Text',
          length: 30,
          nullable: true,
          primaryKey: false,
          foreignKey: false,
          autoIncrement: false
        },
        {
          id: 'col-5',
          name: 'Phone',
          displayName: 'Phone',
          dataType: 'Text',
          length: 24,
          nullable: true,
          primaryKey: false,
          foreignKey: false,
          autoIncrement: false
        },
        {
          id: 'col-6',
          name: 'Country',
          displayName: 'Country',
          dataType: 'Text',
          length: 15,
          nullable: true,
          primaryKey: false,
          foreignKey: false,
          autoIncrement: false
        }
      ]
    },
    layoutType: FormLayoutType.SINGLE,
    dataControl: DataControlType.ADO_DATA,
    fields: [],
    navigationButtons: [
      { id: 'btn-first', type: 'first', caption: 'First', enabled: true, visible: true },
      { id: 'btn-previous', type: 'previous', caption: 'Previous', enabled: true, visible: true },
      { id: 'btn-next', type: 'next', caption: 'Next', enabled: true, visible: true },
      { id: 'btn-last', type: 'last', caption: 'Last', enabled: true, visible: true },
      { id: 'btn-add', type: 'add', caption: 'Add New', enabled: true, visible: true },
      { id: 'btn-delete', type: 'delete', caption: 'Delete', enabled: true, visible: true },
      { id: 'btn-update', type: 'update', caption: 'Update', enabled: true, visible: true },
      { id: 'btn-cancel', type: 'cancel', caption: 'Cancel', enabled: true, visible: true },
      { id: 'btn-refresh', type: 'refresh', caption: 'Refresh', enabled: true, visible: true }
    ],
    formProperties: {
      caption: 'Customer Data Entry',
      width: 480,
      height: 360,
      resizable: true,
      centerOnScreen: true,
      showInTaskbar: true,
      modal: false
    },
    codeGeneration: {
      generateValidation: true,
      generateErrorHandling: true,
      generateNavigation: true,
      generateSearch: false,
      includeComments: true,
      useTryBlocks: false
    }
  });

  const totalSteps = 6;
  const [availableConnections] = useState<DatabaseConnection[]>([
    wizardData.connection,
    {
      id: 'conn-2',
      name: 'Products Database',
      type: DataSourceType.SQL_SERVER,
      connectionString: 'Server=localhost;Database=Products;Trusted_Connection=true',
      provider: 'SQLOLEDB',
      server: 'localhost',
      database: 'Products',
      isConnected: false
    },
    {
      id: 'conn-3',
      name: 'Orders Database',
      type: DataSourceType.ODBC,
      connectionString: 'DSN=Orders;UID=admin;PWD=password',
      provider: 'MSDASQL',
      isConnected: false
    }
  ]);
  
  const [availableTables] = useState<DatabaseTable[]>([
    wizardData.table,
    {
      id: 'table-2',
      name: 'Products',
      schema: 'dbo',
      type: 'table',
      recordCount: 77,
      columns: [
        {
          id: 'col-p1',
          name: 'ProductID',
          displayName: 'Product ID',
          dataType: 'Integer',
          nullable: false,
          primaryKey: true,
          foreignKey: false,
          autoIncrement: true
        },
        {
          id: 'col-p2',
          name: 'ProductName',
          displayName: 'Product Name',
          dataType: 'Text',
          length: 40,
          nullable: false,
          primaryKey: false,
          foreignKey: false,
          autoIncrement: false
        },
        {
          id: 'col-p3',
          name: 'UnitPrice',
          displayName: 'Unit Price',
          dataType: 'Currency',
          nullable: true,
          primaryKey: false,
          foreignKey: false,
          autoIncrement: false
        },
        {
          id: 'col-p4',
          name: 'UnitsInStock',
          displayName: 'Units In Stock',
          dataType: 'Integer',
          nullable: true,
          primaryKey: false,
          foreignKey: false,
          autoIncrement: false
        }
      ]
    },
    {
      id: 'table-3',
      name: 'Orders',
      schema: 'dbo',
      type: 'table',
      recordCount: 830,
      columns: [
        {
          id: 'col-o1',
          name: 'OrderID',
          displayName: 'Order ID',
          dataType: 'Integer',
          nullable: false,
          primaryKey: true,
          foreignKey: false,
          autoIncrement: true
        },
        {
          id: 'col-o2',
          name: 'CustomerID',
          displayName: 'Customer ID',
          dataType: 'Text',
          length: 5,
          nullable: true,
          primaryKey: false,
          foreignKey: true,
          autoIncrement: false
        },
        {
          id: 'col-o3',
          name: 'OrderDate',
          displayName: 'Order Date',
          dataType: 'Date',
          nullable: true,
          primaryKey: false,
          foreignKey: false,
          autoIncrement: false
        },
        {
          id: 'col-o4',
          name: 'ShipAddress',
          displayName: 'Ship Address',
          dataType: 'Text',
          length: 60,
          nullable: true,
          primaryKey: false,
          foreignKey: false,
          autoIncrement: false
        }
      ]
    }
  ]);

  useEffect(() => {
    if (wizardData.table && wizardData.fields.length === 0) {
      // Auto-generate fields from table columns
      const generatedFields: FormField[] = wizardData.table.columns.map((column, index) => ({
        id: `field-${column.id}`,
        columnId: column.id,
        controlType: getDefaultControlType(column),
        label: column.displayName,
        required: !column.nullable,
        readOnly: column.primaryKey && column.autoIncrement,
        visible: true,
        tabOrder: index
      }));
      
      setWizardData({
        ...wizardData,
        fields: generatedFields
      });
    }
  }, [wizardData.table]);

  const getDefaultControlType = (column: DatabaseColumn): ControlType => {
    if (column.dataType.toLowerCase().includes('text') || column.dataType.toLowerCase().includes('char')) {
      return column.length && column.length > 50 ? ControlType.RICH_TEXTBOX : ControlType.TEXTBOX;
    }
    if (column.dataType.toLowerCase().includes('date')) {
      return ControlType.DATE_PICKER;
    }
    if (column.dataType.toLowerCase().includes('bool')) {
      return ControlType.CHECKBOX;
    }
    if (column.dataType.toLowerCase().includes('memo')) {
      return ControlType.RICH_TEXTBOX;
    }
    return ControlType.TEXTBOX;
  };

  const generateFormCode = (): string => {
    let code = `VERSION 5.00\n`;
    code += `Object = "{67397AA1-7FB1-11D0-B148-00A0C922E820}#6.0#0"; "MSADODC.OCX"\n`;
    code += `Begin VB.Form ${wizardData.name}\n`;
    code += `   Caption         =   "${wizardData.formProperties.caption}"\n`;
    code += `   ClientHeight    =   ${wizardData.formProperties.height * 15}\n`;
    code += `   ClientLeft      =   ${120}\n`;
    code += `   ClientTop       =   ${465}\n`;
    code += `   ClientWidth     =   ${wizardData.formProperties.width * 15}\n`;
    code += `   LinkTopic       =   "Form1"\n`;
    code += `   ScaleHeight     =   ${wizardData.formProperties.height * 15}\n`;
    code += `   ScaleWidth      =   ${wizardData.formProperties.width * 15}\n`;
    if (!wizardData.formProperties.resizable) {
      code += `   MaxButton       =   0   'False\n`;
    }
    if (wizardData.formProperties.centerOnScreen) {
      code += `   StartUpPosition =   1  'CenterOwner\n`;
    }
    code += `   Begin MSAdodcLib.Adodc Adodc1\n`;
    code += `      Height          =   330\n`;
    code += `      Left            =   120\n`;
    code += `      Top             =   ${(wizardData.formProperties.height - 40) * 15}\n`;
    code += `      Visible         =   0   'False\n`;
    code += `      Width           =   2415\n`;
    code += `      _ExtentX        =   4260\n`;
    code += `      _ExtentY        =   582\n`;
    code += `      ConnectMode     =   0\n`;
    code += `      CursorLocation  =   3\n`;
    code += `      IsolationLevel  =   -1\n`;
    code += `      ConnectionTimeout=   15\n`;
    code += `      CommandTimeout  =   30\n`;
    code += `      CursorType      =   3\n`;
    code += `      LockType        =   3\n`;
    code += `      CommandType     =   2\n`;
    code += `      CursorOptions   =   0\n`;
    code += `      CacheSize       =   50\n`;
    code += `      MaxRecords      =   0\n`;
    code += `      BOFAction       =   0\n`;
    code += `      EOFAction       =   0\n`;
    code += `      ConnectStringType=   1\n`;
    code += `      Appearance      =   1\n`;
    code += `      BackColor       =   -2147483643\n`;
    code += `      ForeColor       =   -2147483640\n`;
    code += `      Orientation     =   0\n`;
    code += `      Enabled         =   -1\n`;
    code += `      Connect         =   "${wizardData.connection.connectionString}"\n`;
    code += `      OLEDBString     =   "${wizardData.connection.connectionString}"\n`;
    code += `      OLEDBFile       =   ""\n`;
    code += `      DataSourceName  =   ""\n`;
    code += `      OtherAttributes =   ""\n`;
    code += `      UserName        =   ""\n`;
    code += `      Password        =   ""\n`;
    code += `      RecordSource    =   "${wizardData.table.name}"\n`;
    code += `      Caption         =   "Adodc1"\n`;
    code += `      _Version        =   393216\n`;
    code += `   End\n`;

    // Generate controls based on layout
    let yPos = 240; // Starting Y position
    const labelWidth = 1200;
    const controlWidth = 1800;
    const controlHeight = 315;
    const spacing = 360;

    wizardData.fields.forEach((field, index) => {
      const column = wizardData.table.columns.find(c => c.id === field.columnId);
      if (!column || !field.visible) return;

      // Label
      code += `   Begin VB.Label lbl${column.name}\n`;
      code += `      Caption         =   "${field.label}"\n`;
      code += `      Height          =   ${controlHeight}\n`;
      code += `      Left            =   240\n`;
      code += `      TabIndex        =   ${index * 2}\n`;
      code += `      Top             =   ${yPos}\n`;
      code += `      Width           =   ${labelWidth}\n`;
      code += `   End\n`;

      // Control
      const controlName = `txt${column.name}`;
      if (field.controlType === ControlType.TEXTBOX) {
        code += `   Begin VB.TextBox ${controlName}\n`;
        code += `      DataField       =   "${column.name}"\n`;
        code += `      DataSource      =   "Adodc1"\n`;
        code += `      Height          =   ${controlHeight}\n`;
        code += `      Left            =   1560\n`;
        code += `      TabIndex        =   ${index * 2 + 1}\n`;
        code += `      Top             =   ${yPos}\n`;
        code += `      Width           =   ${controlWidth}\n`;
        if (field.readOnly) {
          code += `      Locked          =   -1  'True\n`;
          code += `      BackColor       =   &H8000000F&\n`;
        }
        code += `   End\n`;
      } else if (field.controlType === ControlType.CHECKBOX) {
        code += `   Begin VB.CheckBox ${controlName}\n`;
        code += `      DataField       =   "${column.name}"\n`;
        code += `      DataSource      =   "Adodc1"\n`;
        code += `      Height          =   ${controlHeight}\n`;
        code += `      Left            =   1560\n`;
        code += `      TabIndex        =   ${index * 2 + 1}\n`;
        code += `      Top             =   ${yPos}\n`;
        code += `      Width           =   ${controlWidth}\n`;
        code += `   End\n`;
      }

      yPos += spacing;
    });

    // Navigation buttons
    const buttonWidth = 1000;
    const buttonHeight = 375;
    let buttonX = 240;
    const buttonY = yPos + 240;

    wizardData.navigationButtons.filter(btn => btn.visible).forEach((button, index) => {
      code += `   Begin VB.CommandButton cmd${button.type.charAt(0).toUpperCase() + button.type.slice(1)}\n`;
      code += `      Caption         =   "${button.caption}"\n`;
      code += `      Height          =   ${buttonHeight}\n`;
      code += `      Left            =   ${buttonX}\n`;
      code += `      TabIndex        =   ${100 + index}\n`;
      code += `      Top             =   ${buttonY}\n`;
      code += `      Width           =   ${buttonWidth}\n`;
      code += `   End\n`;
      buttonX += buttonWidth + 120;
    });

    code += `End\n`;
    code += `Attribute VB_Name = "${wizardData.name}"\n`;
    code += `Attribute VB_GlobalNameSpace = False\n`;
    code += `Attribute VB_Creatable = False\n`;
    code += `Attribute VB_PredeclaredId = True\n`;
    code += `Attribute VB_Exposed = False\n\n`;

    if (wizardData.codeGeneration.includeComments) {
      code += `' Data Form generated by VB6 Data Form Wizard\n`;
      code += `' Table: ${wizardData.table.schema}.${wizardData.table.name}\n`;
      code += `' Layout: ${wizardData.layoutType}\n`;
      code += `' Generated on: ${new Date().toLocaleString()}\n\n`;
    }

    // Form events
    code += `Private Sub Form_Load()\n`;
    if (wizardData.codeGeneration.includeComments) {
      code += `    ' Initialize the data connection\n`;
    }
    if (wizardData.codeGeneration.generateErrorHandling) {
      code += `    On Error GoTo ErrorHandler\n    \n`;
    }
    code += `    ' Open the recordset\n`;
    code += `    Adodc1.Refresh\n`;
    if (wizardData.codeGeneration.generateErrorHandling) {
      code += `    \n    Exit Sub\n    \nErrorHandler:\n`;
      code += `    MsgBox "Error loading data: " & Err.Description, vbCritical, "Data Error"\n`;
    }
    code += `End Sub\n\n`;

    // Navigation button events
    wizardData.navigationButtons.filter(btn => btn.visible).forEach(button => {
      const procName = `cmd${button.type.charAt(0).toUpperCase() + button.type.slice(1)}_Click`;
      code += `Private Sub ${procName}()\n`;
      
      if (wizardData.codeGeneration.generateErrorHandling) {
        code += `    On Error GoTo ErrorHandler\n    \n`;
      }

      switch (button.type) {
        case 'first':
          code += `    Adodc1.Recordset.MoveFirst\n`;
          break;
        case 'previous':
          code += `    If Not Adodc1.Recordset.BOF Then\n`;
          code += `        Adodc1.Recordset.MovePrevious\n`;
          code += `        If Adodc1.Recordset.BOF Then Adodc1.Recordset.MoveFirst\n`;
          code += `    End If\n`;
          break;
        case 'next':
          code += `    If Not Adodc1.Recordset.EOF Then\n`;
          code += `        Adodc1.Recordset.MoveNext\n`;
          code += `        If Adodc1.Recordset.EOF Then Adodc1.Recordset.MoveLast\n`;
          code += `    End If\n`;
          break;
        case 'last':
          code += `    Adodc1.Recordset.MoveLast\n`;
          break;
        case 'add':
          code += `    Adodc1.Recordset.AddNew\n`;
          break;
        case 'delete':
          code += `    If MsgBox("Are you sure you want to delete this record?", vbQuestion Or vbYesNo) = vbYes Then\n`;
          code += `        Adodc1.Recordset.Delete\n`;
          code += `        Adodc1.Recordset.MoveNext\n`;
          code += `        If Adodc1.Recordset.EOF Then Adodc1.Recordset.MoveLast\n`;
          code += `    End If\n`;
          break;
        case 'update':
          if (wizardData.codeGeneration.generateValidation) {
            code += `    ' Validate required fields\n`;
            wizardData.fields.filter(f => f.required).forEach(field => {
              const column = wizardData.table.columns.find(c => c.id === field.columnId);
              if (column) {
                code += `    If Trim(txt${column.name}.Text) = "" Then\n`;
                code += `        MsgBox "${field.label} is required.", vbExclamation\n`;
                code += `        txt${column.name}.SetFocus\n`;
                code += `        Exit Sub\n`;
                code += `    End If\n`;
              }
            });
          }
          code += `    Adodc1.Recordset.Update\n`;
          break;
        case 'cancel':
          code += `    Adodc1.Recordset.CancelUpdate\n`;
          code += `    Adodc1.Refresh\n`;
          break;
        case 'refresh':
          code += `    Adodc1.Refresh\n`;
          break;
      }

      if (wizardData.codeGeneration.generateErrorHandling) {
        code += `    \n    Exit Sub\n    \nErrorHandler:\n`;
        code += `    MsgBox "Error: " & Err.Description, vbCritical, "${button.caption} Error"\n`;
      }
      
      code += `End Sub\n\n`;
    });

    // Field validation events if enabled
    if (wizardData.codeGeneration.generateValidation) {
      wizardData.fields.forEach(field => {
        const column = wizardData.table.columns.find(c => c.id === field.columnId);
        if (!column || field.readOnly) return;

        if (field.validation) {
          code += `Private Sub txt${column.name}_Validate(Cancel As Boolean)\n`;
          code += `    Dim fieldValue As String\n`;
          code += `    fieldValue = Trim(txt${column.name}.Text)\n    \n`;

          if (field.required) {
            code += `    ' Check if required field is empty\n`;
            code += `    If fieldValue = "" Then\n`;
            code += `        MsgBox "${field.label} is required.", vbExclamation\n`;
            code += `        Cancel = True\n`;
            code += `        Exit Sub\n`;
            code += `    End If\n    \n`;
          }

          if (field.validation.minLength) {
            code += `    ' Check minimum length\n`;
            code += `    If Len(fieldValue) < ${field.validation.minLength} Then\n`;
            code += `        MsgBox "${field.label} must be at least ${field.validation.minLength} characters.", vbExclamation\n`;
            code += `        Cancel = True\n`;
            code += `        Exit Sub\n`;
            code += `    End If\n    \n`;
          }

          if (field.validation.maxLength) {
            code += `    ' Check maximum length\n`;
            code += `    If Len(fieldValue) > ${field.validation.maxLength} Then\n`;
            code += `        MsgBox "${field.label} cannot exceed ${field.validation.maxLength} characters.", vbExclamation\n`;
            code += `        Cancel = True\n`;
            code += `        Exit Sub\n`;
            code += `    End If\n    \n`;
          }

          if (field.validation.pattern) {
            code += `    ' Pattern validation would go here\n`;
            code += `    ' TODO: Implement regex pattern validation\n    \n`;
          }

          code += `End Sub\n\n`;
        }
      });
    }

    return code;
  };

  const handleSave = () => {
    if (onSave) {
      onSave(wizardData);
    }
    onClose();
  };

  const renderStep1 = () => (
    <div className="space-y-6">
      <h3 className="text-lg font-semibold mb-4">Data Source Selection</h3>
      
      <div className="space-y-4">
        <div>
          <label className="block text-sm font-medium mb-2">Available Data Connections</label>
          <div className="border rounded max-h-48 overflow-y-auto">
            {availableConnections.map(conn => (
              <div
                key={conn.id}
                className={`p-3 border-b cursor-pointer hover:bg-gray-50 ${
                  wizardData.connection.id === conn.id ? 'bg-blue-50 border-blue-200' : ''
                }`}
                onClick={() => setWizardData({ ...wizardData, connection: conn })}
              >
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">{conn.name}</div>
                    <div className="text-sm text-gray-600">{conn.type}</div>
                    <div className="text-xs text-gray-500 font-mono">{conn.database || conn.connectionString}</div>
                  </div>
                  <div className={`w-3 h-3 rounded-full ${conn.isConnected ? 'bg-green-500' : 'bg-red-500'}`} />
                </div>
              </div>
            ))}
          </div>
        </div>
        
        <div className="p-4 bg-gray-50 rounded">
          <h4 className="font-medium mb-2">Selected Connection Details</h4>
          <div className="space-y-2 text-sm">
            <div><strong>Name:</strong> {wizardData.connection.name}</div>
            <div><strong>Type:</strong> {wizardData.connection.type}</div>
            <div><strong>Provider:</strong> {wizardData.connection.provider}</div>
            <div><strong>Connection String:</strong></div>
            <div className="font-mono text-xs bg-white p-2 rounded border break-all">
              {wizardData.connection.connectionString}
            </div>
          </div>
        </div>
        
        <div className="flex gap-2">
          <button className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700">
            New Connection...
          </button>
          <button className="px-4 py-2 border rounded hover:bg-gray-50">
            Test Connection
          </button>
        </div>
      </div>
    </div>
  );

  const renderStep2 = () => (
    <div className="space-y-6">
      <h3 className="text-lg font-semibold mb-4">Table/View Selection</h3>
      
      <div className="space-y-4">
        <div>
          <label className="block text-sm font-medium mb-2">Available Tables and Views</label>
          <div className="border rounded max-h-64 overflow-y-auto">
            {availableTables.map(table => (
              <div
                key={table.id}
                className={`p-3 border-b cursor-pointer hover:bg-gray-50 ${
                  wizardData.table.id === table.id ? 'bg-blue-50 border-blue-200' : ''
                }`}
                onClick={() => setWizardData({ ...wizardData, table })}
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    {table.type === 'table' ? <Table className="w-4 h-4 text-blue-600" /> : <Eye className="w-4 h-4 text-green-600" />}
                    <div>
                      <div className="font-medium">{table.schema}.{table.name}</div>
                      <div className="text-sm text-gray-600">{table.recordCount} records • {table.columns.length} columns</div>
                    </div>
                  </div>
                  <span className="text-xs bg-gray-100 px-2 py-1 rounded">{table.type}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
        
        <div className="p-4 bg-gray-50 rounded">
          <h4 className="font-medium mb-3">Table Structure: {wizardData.table.name}</h4>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b">
                  <th className="text-left p-2">Column</th>
                  <th className="text-left p-2">Type</th>
                  <th className="text-left p-2">Size</th>
                  <th className="text-left p-2">Nullable</th>
                  <th className="text-left p-2">Key</th>
                </tr>
              </thead>
              <tbody>
                {wizardData.table.columns.map(column => (
                  <tr key={column.id} className="border-b hover:bg-white">
                    <td className="p-2 font-medium">{column.name}</td>
                    <td className="p-2">{column.dataType}</td>
                    <td className="p-2">{column.length || column.precision || '-'}</td>
                    <td className="p-2">{column.nullable ? 'Yes' : 'No'}</td>
                    <td className="p-2">
                      {column.primaryKey && <span className="text-xs bg-yellow-100 text-yellow-800 px-1 rounded">PK</span>}
                      {column.foreignKey && <span className="text-xs bg-blue-100 text-blue-800 px-1 rounded ml-1">FK</span>}
                      {column.autoIncrement && <span className="text-xs bg-green-100 text-green-800 px-1 rounded ml-1">AI</span>}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );

  const renderStep3 = () => (
    <div className="space-y-6">
      <h3 className="text-lg font-semibold mb-4">Form Layout</h3>
      
      <div className="space-y-4">
        <div>
          <label className="block text-sm font-medium mb-2">Layout Type</label>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {Object.values(FormLayoutType).map(layout => (
              <div
                key={layout}
                className={`p-4 border rounded cursor-pointer hover:bg-gray-50 ${
                  wizardData.layoutType === layout ? 'border-blue-500 bg-blue-50' : ''
                }`}
                onClick={() => setWizardData({ ...wizardData, layoutType: layout })}
              >
                <div className="flex items-center gap-3">
                  {layout === FormLayoutType.SINGLE && <FileText className="w-6 h-6 text-blue-600" />}
                  {layout === FormLayoutType.TABULAR && <Grid className="w-6 h-6 text-green-600" />}
                  {layout === FormLayoutType.MASTER_DETAIL && <List className="w-6 h-6 text-purple-600" />}
                  {layout === FormLayoutType.COLUMNAR && <Columns className="w-6 h-6 text-orange-600" />}
                  {layout === FormLayoutType.FREEFORM && <Layout className="w-6 h-6 text-red-600" />}
                  <div>
                    <div className="font-medium">{layout}</div>
                    <div className="text-sm text-gray-600">
                      {layout === FormLayoutType.SINGLE && 'One record at a time with individual controls'}
                      {layout === FormLayoutType.TABULAR && 'Multiple records in a grid format'}
                      {layout === FormLayoutType.MASTER_DETAIL && 'Parent record with related child records'}
                      {layout === FormLayoutType.COLUMNAR && 'Labels above controls in columns'}
                      {layout === FormLayoutType.FREEFORM && 'Custom layout with manual positioning'}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
        
        <div>
          <label className="block text-sm font-medium mb-2">Data Control Type</label>
          <select
            value={wizardData.dataControl}
            onChange={(e) => setWizardData({ ...wizardData, dataControl: e.target.value as DataControlType })}
            className="w-full px-3 py-2 border rounded focus:ring-2 focus:ring-blue-500"
          >
            {Object.values(DataControlType).map(control => (
              <option key={control} value={control}>{control}</option>
            ))}
          </select>
        </div>
        
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium mb-1">Form Width</label>
            <input
              type="number"
              value={wizardData.formProperties.width}
              onChange={(e) => setWizardData({
                ...wizardData,
                formProperties: { ...wizardData.formProperties, width: parseInt(e.target.value) || 480 }
              })}
              className="w-full px-3 py-2 border rounded focus:ring-2 focus:ring-blue-500"
              min="320"
              max="800"
            />
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Form Height</label>
            <input
              type="number"
              value={wizardData.formProperties.height}
              onChange={(e) => setWizardData({
                ...wizardData,
                formProperties: { ...wizardData.formProperties, height: parseInt(e.target.value) || 360 }
              })}
              className="w-full px-3 py-2 border rounded focus:ring-2 focus:ring-blue-500"
              min="240"
              max="600"
            />
          </div>
        </div>
        
        <div>
          <label className="block text-sm font-medium mb-1">Form Caption</label>
          <input
            type="text"
            value={wizardData.formProperties.caption}
            onChange={(e) => setWizardData({
              ...wizardData,
              formProperties: { ...wizardData.formProperties, caption: e.target.value }
            })}
            className="w-full px-3 py-2 border rounded focus:ring-2 focus:ring-blue-500"
          />
        </div>
        
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={wizardData.formProperties.resizable}
                onChange={(e) => setWizardData({
                  ...wizardData,
                  formProperties: { ...wizardData.formProperties, resizable: e.target.checked }
                })}
              />
              Resizable
            </label>
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={wizardData.formProperties.centerOnScreen}
                onChange={(e) => setWizardData({
                  ...wizardData,
                  formProperties: { ...wizardData.formProperties, centerOnScreen: e.target.checked }
                })}
              />
              Center on screen
            </label>
          </div>
          <div className="space-y-2">
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={wizardData.formProperties.showInTaskbar}
                onChange={(e) => setWizardData({
                  ...wizardData,
                  formProperties: { ...wizardData.formProperties, showInTaskbar: e.target.checked }
                })}
              />
              Show in taskbar
            </label>
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={wizardData.formProperties.modal}
                onChange={(e) => setWizardData({
                  ...wizardData,
                  formProperties: { ...wizardData.formProperties, modal: e.target.checked }
                })}
              />
              Modal dialog
            </label>
          </div>
        </div>
      </div>
    </div>
  );

  const renderStep4 = () => (
    <div className="space-y-6">
      <h3 className="text-lg font-semibold mb-4">Field Configuration</h3>
      
      <div className="space-y-4 max-h-96 overflow-y-auto">
        {wizardData.fields.map(field => {
          const column = wizardData.table.columns.find(c => c.id === field.columnId);
          if (!column) return null;
          
          return (
            <div key={field.id} className="border rounded p-4">
              <div className="grid grid-cols-4 gap-4 mb-3">
                <div>
                  <label className="block text-sm font-medium mb-1">Field</label>
                  <div className="text-sm font-mono bg-gray-100 p-2 rounded">{column.name}</div>
                </div>
                <div>
                  <label className="block text-sm font-medium mb-1">Label</label>
                  <input
                    type="text"
                    value={field.label}
                    onChange={(e) => setWizardData({
                      ...wizardData,
                      fields: wizardData.fields.map(f =>
                        f.id === field.id ? { ...f, label: e.target.value } : f
                      )
                    })}
                    className="w-full px-2 py-1 border rounded text-sm"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium mb-1">Control Type</label>
                  <select
                    value={field.controlType}
                    onChange={(e) => setWizardData({
                      ...wizardData,
                      fields: wizardData.fields.map(f =>
                        f.id === field.id ? { ...f, controlType: e.target.value as ControlType } : f
                      )
                    })}
                    className="w-full px-2 py-1 border rounded text-sm"
                  >
                    {Object.values(ControlType).map(type => (
                      <option key={type} value={type}>{type}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium mb-1">Tab Order</label>
                  <input
                    type="number"
                    value={field.tabOrder}
                    onChange={(e) => setWizardData({
                      ...wizardData,
                      fields: wizardData.fields.map(f =>
                        f.id === field.id ? { ...f, tabOrder: parseInt(e.target.value) || 0 } : f
                      )
                    })}
                    className="w-full px-2 py-1 border rounded text-sm"
                    min="0"
                  />
                </div>
              </div>
              
              <div className="flex items-center gap-6 mb-3">
                <label className="flex items-center gap-2 text-sm">
                  <input
                    type="checkbox"
                    checked={field.visible}
                    onChange={(e) => setWizardData({
                      ...wizardData,
                      fields: wizardData.fields.map(f =>
                        f.id === field.id ? { ...f, visible: e.target.checked } : f
                      )
                    })}
                  />
                  Visible
                </label>
                <label className="flex items-center gap-2 text-sm">
                  <input
                    type="checkbox"
                    checked={field.required}
                    onChange={(e) => setWizardData({
                      ...wizardData,
                      fields: wizardData.fields.map(f =>
                        f.id === field.id ? { ...f, required: e.target.checked } : f
                      )
                    })}
                  />
                  Required
                </label>
                <label className="flex items-center gap-2 text-sm">
                  <input
                    type="checkbox"
                    checked={field.readOnly}
                    onChange={(e) => setWizardData({
                      ...wizardData,
                      fields: wizardData.fields.map(f =>
                        f.id === field.id ? { ...f, readOnly: e.target.checked } : f
                      )
                    })}
                  />
                  Read Only
                </label>
              </div>
              
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <label className="block font-medium mb-1">Validation</label>
                  <div className="space-y-1">
                    <input
                      type="number"
                      placeholder="Min length"
                      value={field.validation?.minLength || ''}
                      onChange={(e) => setWizardData({
                        ...wizardData,
                        fields: wizardData.fields.map(f =>
                          f.id === field.id ? {
                            ...f,
                            validation: { ...f.validation, minLength: parseInt(e.target.value) || undefined }
                          } : f
                        )
                      })}
                      className="w-full px-2 py-1 border rounded"
                    />
                    <input
                      type="number"
                      placeholder="Max length"
                      value={field.validation?.maxLength || ''}
                      onChange={(e) => setWizardData({
                        ...wizardData,
                        fields: wizardData.fields.map(f =>
                          f.id === field.id ? {
                            ...f,
                            validation: { ...f.validation, maxLength: parseInt(e.target.value) || undefined }
                          } : f
                        )
                      })}
                      className="w-full px-2 py-1 border rounded"
                    />
                  </div>
                </div>
                <div>
                  <label className="block font-medium mb-1">Formatting</label>
                  <div className="space-y-1">
                    <input
                      type="text"
                      placeholder="Format string"
                      value={field.formatting?.format || ''}
                      onChange={(e) => setWizardData({
                        ...wizardData,
                        fields: wizardData.fields.map(f =>
                          f.id === field.id ? {
                            ...f,
                            formatting: { ...f.formatting, format: e.target.value }
                          } : f
                        )
                      })}
                      className="w-full px-2 py-1 border rounded"
                    />
                    <select
                      value={field.formatting?.alignment || 'left'}
                      onChange={(e) => setWizardData({
                        ...wizardData,
                        fields: wizardData.fields.map(f =>
                          f.id === field.id ? {
                            ...f,
                            formatting: { ...f.formatting, alignment: e.target.value as any }
                          } : f
                        )
                      })}
                      className="w-full px-2 py-1 border rounded"
                    >
                      <option value="left">Left</option>
                      <option value="center">Center</option>
                      <option value="right">Right</option>
                    </select>
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );

  const renderStep5 = () => (
    <div className="space-y-6">
      <h3 className="text-lg font-semibold mb-4">Navigation & Code Generation</h3>
      
      <div className="grid grid-cols-2 gap-6">
        <div>
          <h4 className="font-medium mb-3">Navigation Buttons</h4>
          <div className="space-y-2">
            {wizardData.navigationButtons.map(button => (
              <div key={button.id} className="flex items-center gap-3 p-2 border rounded">
                <input
                  type="checkbox"
                  checked={button.visible}
                  onChange={(e) => setWizardData({
                    ...wizardData,
                    navigationButtons: wizardData.navigationButtons.map(btn =>
                      btn.id === button.id ? { ...btn, visible: e.target.checked } : btn
                    )
                  })}
                />
                <input
                  type="text"
                  value={button.caption}
                  onChange={(e) => setWizardData({
                    ...wizardData,
                    navigationButtons: wizardData.navigationButtons.map(btn =>
                      btn.id === button.id ? { ...btn, caption: e.target.value } : btn
                    )
                  })}
                  className="flex-1 px-2 py-1 border rounded text-sm"
                />
                <span className="text-xs text-gray-600 w-16">{button.type}</span>
              </div>
            ))}
          </div>
        </div>
        
        <div>
          <h4 className="font-medium mb-3">Code Generation Options</h4>
          <div className="space-y-3">
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={wizardData.codeGeneration.generateValidation}
                onChange={(e) => setWizardData({
                  ...wizardData,
                  codeGeneration: { ...wizardData.codeGeneration, generateValidation: e.target.checked }
                })}
              />
              Generate field validation
            </label>
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={wizardData.codeGeneration.generateErrorHandling}
                onChange={(e) => setWizardData({
                  ...wizardData,
                  codeGeneration: { ...wizardData.codeGeneration, generateErrorHandling: e.target.checked }
                })}
              />
              Generate error handling
            </label>
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={wizardData.codeGeneration.generateNavigation}
                onChange={(e) => setWizardData({
                  ...wizardData,
                  codeGeneration: { ...wizardData.codeGeneration, generateNavigation: e.target.checked }
                })}
              />
              Generate navigation code
            </label>
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={wizardData.codeGeneration.generateSearch}
                onChange={(e) => setWizardData({
                  ...wizardData,
                  codeGeneration: { ...wizardData.codeGeneration, generateSearch: e.target.checked }
                })}
              />
              Generate search functionality
            </label>
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={wizardData.codeGeneration.includeComments}
                onChange={(e) => setWizardData({
                  ...wizardData,
                  codeGeneration: { ...wizardData.codeGeneration, includeComments: e.target.checked }
                })}
              />
              Include code comments
            </label>
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={wizardData.codeGeneration.useTryBlocks}
                onChange={(e) => setWizardData({
                  ...wizardData,
                  codeGeneration: { ...wizardData.codeGeneration, useTryBlocks: e.target.checked }
                })}
              />
              Use Try/Catch blocks (VB.NET style)
            </label>
          </div>
        </div>
      </div>
      
      <div className="p-4 bg-blue-50 border border-blue-200 rounded">
        <h4 className="font-medium text-blue-800 mb-2 flex items-center gap-2">
          <Info className="w-4 h-4" />
          Form Preview
        </h4>
        <div className="text-sm text-blue-700 space-y-1">
          <div>Table: <strong>{wizardData.table.schema}.{wizardData.table.name}</strong></div>
          <div>Layout: <strong>{wizardData.layoutType}</strong></div>
          <div>Visible Fields: <strong>{wizardData.fields.filter(f => f.visible).length}</strong></div>
          <div>Navigation Buttons: <strong>{wizardData.navigationButtons.filter(b => b.visible).length}</strong></div>
        </div>
      </div>
    </div>
  );

  const renderStep6 = () => (
    <div className="space-y-6">
      <h3 className="text-lg font-semibold mb-4">Generated Code Preview</h3>
      
      <div className="flex gap-2 mb-4">
        <button
          onClick={() => navigator.clipboard.writeText(generateFormCode())}
          className="px-3 py-1.5 bg-blue-600 text-white rounded text-sm hover:bg-blue-700 flex items-center gap-1"
        >
          <Copy className="w-4 h-4" />
          Copy Form Code
        </button>
        <button
          onClick={() => {
            const blob = new Blob([generateFormCode()], { type: 'text/plain' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `${wizardData.name}.frm`;
            a.click();
            URL.revokeObjectURL(url);
          }}
          className="px-3 py-1.5 bg-green-600 text-white rounded text-sm hover:bg-green-700 flex items-center gap-1"
        >
          <Download className="w-4 h-4" />
          Download Form
        </button>
      </div>
      
      <div>
        <h4 className="font-medium mb-2">Visual Basic 6 Form (.frm)</h4>
        <div className="border rounded">
          <pre className="text-xs font-mono bg-gray-900 text-gray-100 p-4 rounded overflow-x-auto h-96">
            {generateFormCode()}
          </pre>
        </div>
      </div>
      
      <div className="grid grid-cols-2 gap-4">
        <div className="bg-green-50 border border-green-200 rounded p-4">
          <h4 className="font-medium text-green-800 mb-2 flex items-center gap-2">
            <Check className="w-4 h-4" />
            What's Included
          </h4>
          <ul className="text-sm text-green-700 space-y-1">
            <li>• ADO Data Control configuration</li>
            <li>• Data-bound controls for each field</li>
            <li>• Navigation button handlers</li>
            {wizardData.codeGeneration.generateValidation && <li>• Field validation logic</li>}
            {wizardData.codeGeneration.generateErrorHandling && <li>• Error handling routines</li>}
            <li>• Form initialization code</li>
            <li>• Database connection management</li>
          </ul>
        </div>
        
        <div className="bg-yellow-50 border border-yellow-200 rounded p-4">
          <h4 className="font-medium text-yellow-800 mb-2 flex items-center gap-2">
            <AlertTriangle className="w-4 h-4" />
            Next Steps
          </h4>
          <ul className="text-sm text-yellow-700 space-y-1">
            <li>• Add the form to your VB6 project</li>
            <li>• Verify database connection string</li>
            <li>• Test form functionality</li>
            <li>• Customize UI appearance as needed</li>
            <li>• Add additional business logic</li>
            <li>• Configure security permissions</li>
          </ul>
        </div>
      </div>
      
      <div className="bg-blue-50 border border-blue-200 rounded p-4">
        <h4 className="font-medium text-blue-800 mb-2 flex items-center gap-2">
          <Info className="w-4 h-4" />
          Summary
        </h4>
        <div className="text-sm text-blue-700 space-y-1">
          <div>Form Name: <strong>{wizardData.name}</strong></div>
          <div>Data Source: <strong>{wizardData.connection.name}</strong></div>
          <div>Table: <strong>{wizardData.table.name}</strong></div>
          <div>Layout: <strong>{wizardData.layoutType}</strong></div>
          <div>Controls: <strong>{wizardData.fields.filter(f => f.visible).length} data fields</strong></div>
          <div>Navigation: <strong>{wizardData.navigationButtons.filter(b => b.visible).length} buttons</strong></div>
        </div>
      </div>
    </div>
  );

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg shadow-xl w-[90%] h-[85%] max-w-6xl flex flex-col">
        {/* Header */}
        <div className="p-4 border-b flex justify-between items-center">
          <div className="flex items-center gap-3">
            <Database className="w-5 h-5 text-blue-600" />
            <h2 className="text-lg font-semibold">Data Form Wizard</h2>
            <span className="text-sm text-gray-600">
              Step {currentStep} of {totalSteps}
            </span>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-gray-100 rounded-lg"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Progress */}
        <div className="px-4 py-2 border-b bg-gray-50">
          <div className="flex items-center justify-between text-sm">
            <div className="flex items-center gap-4">
              {Array.from({ length: totalSteps }, (_, i) => i + 1).map(step => (
                <div
                  key={step}
                  className={`flex items-center gap-2 ${
                    step === currentStep ? 'text-blue-600' : step < currentStep ? 'text-green-600' : 'text-gray-400'
                  }`}
                >
                  <div
                    className={`w-6 h-6 rounded-full flex items-center justify-center text-xs ${
                      step === currentStep ? 'bg-blue-100 border-2 border-blue-600' :
                      step < currentStep ? 'bg-green-100 border-2 border-green-600' :
                      'bg-gray-100 border-2 border-gray-300'
                    }`}
                  >
                    {step < currentStep ? <Check className="w-3 h-3" /> : step}
                  </div>
                  <span className="font-medium">
                    {step === 1 ? 'Data Source' :
                     step === 2 ? 'Table' :
                     step === 3 ? 'Layout' :
                     step === 4 ? 'Fields' :
                     step === 5 ? 'Options' : 'Generate'}
                  </span>
                  {step < totalSteps && <ChevronRight className="w-4 h-4 text-gray-400" />}
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 p-6 overflow-auto">
          {currentStep === 1 && renderStep1()}
          {currentStep === 2 && renderStep2()}
          {currentStep === 3 && renderStep3()}
          {currentStep === 4 && renderStep4()}
          {currentStep === 5 && renderStep5()}
          {currentStep === 6 && renderStep6()}
        </div>

        {/* Navigation */}
        <div className="p-4 border-t bg-gray-50 flex justify-between">
          <button
            onClick={() => setCurrentStep(Math.max(1, currentStep - 1))}
            disabled={currentStep === 1}
            className="px-4 py-2 border rounded hover:bg-gray-100 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
          >
            <ChevronLeft className="w-4 h-4" />
            Previous
          </button>
          
          <div className="flex gap-2">
            {currentStep === totalSteps ? (
              <button
                onClick={handleSave}
                className="px-6 py-2 bg-green-600 text-white rounded hover:bg-green-700 flex items-center gap-2"
              >
                <Check className="w-4 h-4" />
                Create Form
              </button>
            ) : (
              <button
                onClick={() => setCurrentStep(Math.min(totalSteps, currentStep + 1))}
                className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 flex items-center gap-2"
              >
                Next
                <ChevronRight className="w-4 h-4" />
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};